#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs as logs
from waflib import Utils as utils

def options(opt):
	opt.load('compiler_c gnu_dirs')

def configure(ctx):
	ctx.load('compiler_c gnu_dirs')

	ctx.check_cc(lib='m', uselib_store='M', mandatory=True)
	ctx.check_cc(fragment = 'int main () {return 0;}\n', mandatory=True);

	ctx.check_cfg(atleast_pkgconfig_version='0.26')
	ctx.check_cfg(package='dbus-1', uselib_store='DBUS', args=['--cflags', '--libs'], mandatory=True)

	ctx.env.CFLAGS = ['-ggdb', '-Wall']
	ctx.define('DEBUG',1)


def build(bld):

	if bld.cmd == 'install' and bld.cmd == 'uninstall':
		logs.fatal ("Do not install this crapdemo")


	server = bld.program(
			features = ['c'],
			target = '../../server-ref.bin',
			source = bld.path.ant_glob(['server-ref.c']),
			uselib = 'M DBUS',
			install_path = "${BINDIR}"
		)

	client = bld.program(
			features = ['c'],
			target = '../../client-ref.bin',
			source = bld.path.ant_glob(['client-ref.c']),
			uselib = 'M DBUS',
			install_path = "${BINDIR}"
		)
